### ISSUE TITLE
[Feature Request] Review timeout / retries and reconnection configuration for the client connection

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-node#119]

**Comment by bergundy** [comment]
@vitarb once you're done with this work in core can you do this one please?

**Comment by bergundy** [comment]
@vitarb looks like in Java we have both [gRPC level retries](https://github.com/temporalio/sdk-java/tree/6e21990343467afe4b0d63e80c7016800147728e/temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry) and [SDK level retries](https://github.com/temporalio/sdk-java/blob/6e21990343467afe4b0d63e80c7016800147728e/temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionUtils.java#L203).

I'll take care of exposing the retry configuration, you can use some sane defaults for now.

**Comment by bergundy** [comment]
Related:
- https://github.com/temporalio/sdk-java/pull/709
- https://github.com/temporalio/sdk-java/issues/653
- https://github.com/temporalio/sdk-java/issues/666

**Comment by bergundy** [comment]
@Sushisource are you handling this now?

**Comment by Sushisource** [comment]
@bergundy Yeah I'll handle it.

**Comment by Sushisource** [comment]
Closing this since the retryer exists, is configurable, and does not retry deadline exceeded errors by default which is the right thing to do. The Java change dealt with automatic deadline propagation, but it seems that won't happen in `grpc-js`:

https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/constants.ts#L46
