### ISSUE TITLE
[Feature Request] Organize samples in repo

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-node#136]
Currently the samples live in the `create-project` package and are not easily browsable.
The opentelemetry sample added in https://github.com/temporalio/sdk-node/pull/135 is a first attempt to change that by adding a top level samples directory.

Samples share a lot of code and configuration (`tsconfig.json`) which we should strive not to duplicate.
A simple solution to keep the code browsable while avoiding duplication is to symlink shared files.
We should also move the `tsconfig.json` definitions out of the script body and into actual files.
There will still be duplication within the sample files but I think that's a good enough compromise.
All samples should have automated testing.

**Comment by joebowbeer** [comment]
What is relationship between samples here and in https://github.com/temporalio/samples-node ?

**Comment by bergundy** [comment]
Right now, we have samples in both repos, `samples-node` is relatively new.
We will move most of the samples into that repo once it has automated testing and linting.

**Comment by bergundy** [comment]
As discussed yesterday, @lorensr will take care of:
- [ ] Moving the opentelemetry and mtls samples from this repo into the samples-node repo
- [ ] Modifying the package initializer to pull samples from the samples-node repo
- [ ] CI in the samples-node repo

**Comment by lorensr** [comment]
I'll symlink once https://github.com/temporalio/samples-node/pull/4 is done. Would like to discuss linting & testing on our Tues call

**Comment by lorensr** [comment]
Symlink pros vs cons. Do we want to use them?

> Samples share a lot of code and configuration (tsconfig.json) which we should strive not to duplicate.
> A simple solution to keep the code browsable while avoiding duplication is to symlink shared files.


![image](https://user-images.githubusercontent.com/251288/134042947-29754ca0-1f7d-4210-a68e-21b5fe8eae0e.png)

Pros:

- When we update one of the shared files, we only have to update a single file

Cons:

- From @vkarpov15 : My only concern is that the shared config adds friction for devs that want to copy one of the samples into a separate repo using `cp -r`. 
- Not as browsable on GitHub. Instead of seeing the file, you get a line of text and have to go navigate to the target file yourself:

![image](https://user-images.githubusercontent.com/251288/134043196-bfc595c4-665b-4e68-8bea-c6210ea3bbc2.png)
https://github.com/lorensr/samples-node/blob/p2/hello-world/tsconfig.json

**Comment by joebowbeer** [comment]
Having the samples interdependent via shared config is also a drag on the developer, who just wants to copy and paste one example to get started, but I can understand the trade-off.

However, I would be annoyed and a little frightened if I had to deal with symlinks. How do you even do them portably? I fear that's venturing into husky territory, where I do not go.

**Comment by lorensr** [comment]
Alternative suggestion from Val: precommit hook that copies root tsconfig to each sample

**Comment by bergundy** [comment]
> Alternative suggestion from Val: precommit hook that copies root tsconfig to each sample

I like it, best of both worlds

**Comment by bergundy** [comment]
I'm closing this, the samples have been moved out of this repo into `samples-node`.
Thanks @lorensr for the awesome work on the new `@temporalio/create` package.
